# Generated by Django 5.0.2 on 2024-02-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_rename_earliest_arrival_time_ride_required_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_type',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE')], default=None, max_length=20),
        ),
    ]
