# Generated by Django 4.2.9 on 2024-02-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_alter_ride_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='required_arrival_time',
        ),
        migrations.AddField(
            model_name='ride',
            name='earliest_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 59, 59)),
        ),
        migrations.AddField(
            model_name='ride',
            name='latest_arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 23, 59, 59)),
        ),
    ]
