# Generated by Django 4.2.9 on 2024-02-07 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0004_remove_ride_required_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='earliest_arrival_time',
            new_name='required_arrival_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='latest_arrival_time',
        ),
    ]
